name: ort_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
    ^0.18.0

  # State manager
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.0.1
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0

  # UI
  # cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  intl_phone_field: ^3.2.0
  pinput: ^3.0.1
  lottie: ^2.6.0
  loader_overlay: ^2.3.2
  cached_network_image: ^3.3.0
  easy_stepper: ^0.8.3
  mask_text_input_formatter: ^2.8.0
  package_info_plus: ^5.0.1
  skeleton_text: ^3.0.1
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Http
  http: ^0.13.6
  dio: ^5.0.3

  # Navigation
  go_router: ^11.0.0

  # Utils
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0
  searchfield: ^0.8.8
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.2
  injectable_generator: ^2.1.5
  hive_generator: ^2.0.0
  build_runner: ^2.2.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ruster/playstore.png"
  image_path_android: "assets/icon/ruster/playstore.png"
  min_sdk_android: 21 
  remove_alpha_ios: true 

# For splash screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/ruster/playstore.png
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/ruster/
    - assets/icon/vector/
    - assets/icon/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
